### ISSUE TITLE
Industry hydrogen can't be set to a value higher than 0 TJ

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#101]
```
Calculation Post-calculation validations failed with the following errors: 
* #<Refinery::Slot (in, hydrogen) node=:industry_final_demand_for_chemical_hydrogen> demand (1 PJ) does not match demand from the node (0 KJ) (+1 PJ) 
* #<Refinery::Slot (out, hydrogen) node=:industry_final_demand_for_other_hydrogen> demand (0 KJ) does not match output of the node (1 PJ) (-1,000,000,000 MJ)
```

I get this error.

**Comment by michieldenhaan** [comment]
This is a weird one. Is it possible to overwrite a demand using a sparse graph query if the node has a hard-coded ``~ demand = 0``? In agriculture, hydrogen can be possible but there there is a 1-to-1 mapping with the sparse graph.

For now I've removed hydrogen from industry since it is zero in the starting year anyway
