### ISSUE TITLE
Number of old residences and new number of residences don't add up - which causes the area attributes to not be saved

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#118]
When debugging #92 I found out that the area attributes weren't saved to the `.ad` file because some validations didn't pass. I altered the transformer to make sure [it crashes](https://github.com/quintel/transformer/commit/087092fed3025c2e7a223af4f01ba81e8cb8ac02) when the changes aren't valid. However by default I'm getting:

```
Atlas::InvalidDocumentError: Derived(:"noord-holland") was not valid: Number of residences Numberof old residences (0.0) and number of new residences (7587964.0) don't add up to the total number of residences (1314660.0).
```

I'm not sure how this is possible.

You can reproduce this by running:

```
DATASET=<any id will do> bundle exec rake etsource:export
```

**Comment by michieldenhaan** [comment]
This is because the query for number of new residences is:
refers to ``AREA(number_of_residences)``. This is fine, given that ``AREA(number_of_residences)`` returns the number of residences of the **local** dataset (North Holland) filled in by the user. However, this does not seem to be the case, since 7587964.0 is exactly the number of residences of the parent (NL 2015) dataset.

As discussed earlier, I think it is more intuitive if we can just refer to ``DATASET_INPUT(number_of_inhabitants)`` in the sparse graph query rather than ``AREA(number_of_inhabitants)``. However, we ran into trouble with the ``number_of_cars`` when we tried this..

**Comment by michieldenhaan** [comment]
This is still not working as intended:
![selwerd derived ad etsource-etlocal 2018-06-22 14-11-20 1](https://user-images.githubusercontent.com/32056448/41775935-30650b74-7626-11e8-9f80-0c412c9e4382.png)

**Comment by antw** [comment]
> This is still not working as intended:

How can this be reproduced? A quick export of one region (Utrecht) has the numbers adding up correctly.

Is this from a region where one or both has been customised? If so, which region?

**Comment by michieldenhaan** [comment]
Region is Selwerd, ID = 14883

**Comment by antw** [comment]
This seems to be because `DATASET_INPUT(input_percentage_of_old_residences)` returns the percentage (e.g. `94.0`) rather than a factor (e.g. `0.94`). I seem to recall a discussion some time back about displaying values as percentages and then converting to factors prior to storing them...

```
 - number_of_residences = 4060.0
 - number_of_new_residences = -377580.0
 - number_of_old_residences = 381640.0
```

### Values

| Query | Value |
| :-- | --: |
| `DATASET_INPUT(input_percentage_of_old_residences)` | 94.0 |
| `AREA(number_of_residences)` | 4060.0 |

### Number of old residences

```ruby
# DATASET_INPUT(input_percentage_of_old_residences) * AREA(number_of_residences)
# = 94.0 * 4060.0

381640.0
```

### Number of new residences

```ruby
# (1 - DATASET_INPUT(input_percentage_of_old_residences)) * AREA(number_of_residences)
# = (1 - 94.0) * 4060.0
# = -93 * 4060.0

-377580.0
```

**Comment by michieldenhaan** [comment]
Ah that makes a lot of sense, thanks! We indeed decided on displaying values as % and storing as factors, but I realize now that this behaviour is (probably) not linked to setting the unit of an input field to `'%'`  in the ``interface_elements`` .yml files, but rather to setting the type of a slider group to ``type: slider``. The latter also determines whether an interface element is displayed as an input box or a slider.

I'll experiment a bit with changing the ``type``.


Lonely share with ``unit: '%'`` but not in a ``type: slider`` group:
![etlocal httpsbeta-local energytransitionmodel com 2018-06-25 10-01-21 1](https://user-images.githubusercontent.com/32056448/41837766-c414bf74-785e-11e8-9182-108f3da7a613.png)


Shares in a ``type: slider`` group:
![etlocal httpsbeta-local energytransitionmodel com 2018-06-25 10-00-30](https://user-images.githubusercontent.com/32056448/41837735-aa9d3616-785e-11e8-9065-bd170717b8e2.png)
