### ISSUE TITLE
CSV batch import not working properly

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#120]
I've been testing the csv batch import functionality (see https://github.com/quintel/etlocal/issues/116), but it does not seem to be working as intended. I created a csv file to set the default ETLocal values for all areas to 0 (currently this is either 1 or blank). When I run the migration (which took 3 hours to complete) more than 800.000 values and 800.000 commit messages have been added to the database (15k areas times 60 values). However, in the ETLocal front-end the new values only show up for 49 datasets. These 49 datasets are the first 49 rows in the csv file and all happen to be neighbourhoods of the same municipality. Tested this with a smaller csv file (limited to 150 rows) but the outcome is the same.

Branch name is ``csv-testing``

**Comment by antw** [comment]
It looks like the CSV importer is working as written which is to:

1. For each row, find or create a dataset matching the `area` and `geo_id`.
2. For each column (e.g. `input_households_electricity_demand`, `input_households_solar_pv_demand`, etc) create a commit assigning a new value.

So it seems to me that the importer is doing what it is supposed to, but I'd also agree that it isn't currently fit for purpose.

@michieldenhaan For my sake, can you describe what is *expected* behaviour when importing this CSV?

**Comment by michieldenhaan** [comment]
I would expect that after importing the csv/migrating the database all ETLocal datasets from area's in the csv will have their values updated with the ones specified by the csv (with the accompanying commit message).

So suppose that I want to update the number of inhabitants for area's X, Y, Z. I create a csv with column names ``geo_id``, ``area``, ``number_of_inhabitants`` and ``number_of_inhabitants_description``. Row 2, 3, 4 will contain the relevant info for (respectively) X, Y and Z. After importing the csv, the new number_of_inhabitants will show up when I open the area's in the ETLocal front-end. When I click the 'info' icon next to the number of inhabitants, my commit message will show up.

This only works for the first few datasets in the csv but not for all (see screenshot below, I ran the migration 3 times). The values do show up in my database, but not in the ETLocal front-end. Maybe my ``geo_id``s are not correct or so, because the database values do not seem to be linked to the ETLocal front-end for most datasets..

One downside of this method is that it updates ALL dataset copies of an area, not just the Quintel datasets. In some cases this might be useful (e.g. when we add a new key to the ETLocal front-end and want to provide a default value for all datasets), but in most cases I reckon that we only want to update our own datasets, not other users' clones. Is it difficult to expand the import script such that we can specify which datasets of an area are updated?

Works:
![etlocal httplocalhost3000 2018-06-12 17-35-18](https://user-images.githubusercontent.com/32056448/41300870-0fe8c9d8-6e67-11e8-8131-5fd82195b0ed.png)

Doesn't work:
![etlocal httplocalhost3000 2018-06-12 17-37-59](https://user-images.githubusercontent.com/32056448/41301003-65b83678-6e67-11e8-98c8-b3ffcf0e087e.png)

**Comment by antw** [comment]
I'll investigate this more; in particular to see if we can speed up the importer and also create fewer commits (otherwise the application is quickly going to become unusable on our budget), but ...

> Maybe my geo_ids are not correct or so, because the database values do not seem to be linked to the ETLocal front-end for most datasets..

This does appear to be the case. For example line 63 of the CSV specifies an area called "Babylonienbroek" with a geo ID of "BU7380600". However the database says the geo ID of that region is "BU07380600" (there's an extra "0" after "BU").

**Comment by antw** [comment]
> I'll investigate this more; in particular to see if we can speed up the importer **and also create fewer commits**

Looking at the CSV and the way the importer works, I understand now why it creates so many commits, but also think we can avoid it fairly easily. The problem arises from being able to supply a different commit message for each value being updated: it seems to result in descriptions like "Change value *x* to 0", "Change *y* to 3". Such messages are redundant, since the visitor can already see *what* has changed:

![egl-commits](https://user-images.githubusercontent.com/4383/41910137-b17d2fbc-7940-11e8-92d7-bfb42ae87db4.png)

Instead, the message should describe what has changed, and why. For example:

> Imported new values from xxxxx
>
> xxxxx has provided new default values for this dataset based on research
> from yyyyy. This includes more accurate data for households and blah, blah...

See "[How to Write a Git Commit Message → Why, not how](https://chris.beams.io/posts/git-commit/#why-not-how)"

If the CSV importer instead accepted only a single commit message – with the expectation that the message is generic enough to apply to all regions being updated – we could:

* Create only a single commit per dataset, instead of a commit per value.
* Significantly reduce the size of the CSVs.
* Speed up the import process.

---

I also noticed in the above screenshot a number of redundant commits; changing a value to zero that was already zero. Ideally we would ignore such changes since it makes a mess of the user interface and clutters up the database with unwanted data.

I've no idea what the performance impact would be, but I think it's worth investigating.

**Comment by ChaelKruip** [comment]
> For each row in this csv, the source of the data in that row is typically the same 

Do you mean 'column' in stead of 'row'?

> @antw, @ChaelKruip I hope this is clear, if not let me know!

Thanks for writing this down so clearly @michieldenhaan! I have one request though: can you make separate issues/tickets for the 'topics' in your post? Right now this issue is no longer 'atomic' (about one thing) and the title does no longer cover all the topics. This will help to keep a better overview, prioritise, make the resulting tickets actionable and consequently make progress 😄

**Comment by michieldenhaan** [comment]
Thanks, that's a good one. Created separate issues for each subject. 
'Row' should indeed be 'column' (updated the text).

Closing this issue
