### ISSUE TITLE
The download button seems to be missing

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etlocal#122]
Our testing customer notified me that the download button is gone.

I checked this and found that I can clone a dataset and save changes, but the download button is indeed gone.

@michieldenhaan and @antw I am unsure who to assign. Please reassign when appropriate.

**Comment by DorinevanderVlies** [comment]
@michieldenhaan explained that the download button was replaced by a rake task: `rake etsource:export DATASET=<id>`

**Comment by michieldenhaan** [comment]
For future reference:

We decided to remove the download button because it did not provide the functionality we were looking for. The idea was that a user could click on the download button, send us the zip file and that we could unzip it in ``etsource/datasets``. However, it turned out that it wasn't possible to symlink folders like load_profiles and curves this way.

As an alternative, Gerard added a unique ID to each dataset (see below). The user can simply send the relevant IDs and you can run ``rake etsource:export DATASET=<id>`` in your terminal (from ETLocal). Make sure that ``EXPORT_ROOT="https://beta-local.energytransitionmodel.com/"`` in your ``.env`` file.

![etlocal httpsbeta-local energytransitionmodel com 2018-06-21 09-16-35 1](https://user-images.githubusercontent.com/32056448/41703519-e0d6f8b2-7533-11e8-9a3d-af31f728b623.png)
