### ISSUE TITLE
Reduce number of commit messages when updating datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#128]
Currently, when updating values in ETLocal each value gets its own, often redundant, commit message. This leads to a lot of database entries.

The current dataset generation process is as follows:
To generate datasets, we use data from various sources. This data is put into one excel file and subsequently combined and transformed. Ultimately, the excel file generates a csv output file in which (transformed) data is mapped to ETLocal input fields for each region:
![post1](https://user-images.githubusercontent.com/32056448/42211894-f1860614-7eb4-11e8-8283-eacda9d305c4.png)

For each column in this csv, the source of the data in that row is typically the same (e.g. the source for ``input_households_electricity_demand`` is typically the same for all regions in the csv). In addition, various columns have the same source (e.g. the data for input fields 1 till 3 may come from the same source). I expect that when generating a bunch of datasets, around 20-30 unique commit messages can cover 99% of all updated values.

To reduce the number of commit messages, we can group multiple input field updates into one commit, like so:
![post2](https://user-images.githubusercontent.com/32056448/42211920-fe2d7032-7eb4-11e8-9428-e301ae5888cc.png)

I.e. commit message 1 is applied to input fields 1 till 3, commit message 2 is applied to input fields 4 and 5. Per region, this would reduce the number of commit messages for a full dataset update from around 450 to around 20-30.

Since nearly all of the Quintel generated datasets will probably use the same 20-30 commit messages, it may be even better still, if technically possible, if these messages only have to be stored once. In this way, the total number of commit messages in the database would be 20-30 (+ some custom messages), rather than 20-30 _per dataset_. (The same holds for input field values by the way, e.g. most likely we will want to set the whole industry sector to 0 for all neighbourhoods).

Ideally, it should be _possible_ to set individual commit messages per region and per value in the csv, but also to use one message for multiple values/regions, with as little database entries as necessary. The latter is more important.

We discussed whether we should be able to generate datasets by running one script with one csv file or whether we should create one csv file per commit (i.e. one csv file per unique commit message). I strongly prefer the former: with 20-30 unique commit messages it would be very cumbersome if we have to generate 30 csv's.

_Actions:_
- Investigate possibilities for reducing the number of commits/commit messages/database entries

Supersedes: https://github.com/quintel/etlocal/issues/120

**Comment by antw** [comment]
> I.e. commit message 1 is applied to input fields 1 till 3, commit message 2 is applied to input fields 4 and 5. Per region, this would reduce the number of commit messages for a full dataset update from around 450 to around 20-30.
>
> [...]
>
> To reduce the number of commit messages, we can group multiple input field updates into one commit, like so [...]

My main concern with this was that it wouldn't be allowed to have columns with the same name ("Commit message"). It turns out that the CSV library does indeed allow it, so it should not be too difficult to implement.

I've also realised that while we can reduce the number of commits created, we cannot do anything about the number of "dataset edits" for which there is one created per value changed. However, we can remove superfluous information from that database table – such as `created_at` and `updated_at` – since the commit already has that information.

---

I'm still a bit confused by we should allow different *datasets* to have different messages; why would "Region 2" need a different commit message for "ETLocal input field 1-3" than "Region 1"? If we can do away with this requirement, an alternative would be to have a CSV file describing all the data, and a YAML file describing the commit messages. For example:

| area | field 1 | field 2 | field 3 | field 4 | field 5 |
| :--- | :--: | :--: | :--: | :--: | :--: |
| region 1 | 52 | 26 | 96 | FALSE | Municipality |
| region 2 | 89 | 29 | 5 | FALSE | Municipality |
| region 3 | 76 | 38 | 15 | FALSE | Municipality |

```yaml
---
- fields:
    - field 1
    - field 2
    - field 3
  message:
    <message 1>

- fields:
    - field 4
    - field 5
  message:
    <message 2>
```

This has the bonus of allowing multi-line messages, and not having to store identical commit messages for every dataset.

---

> Since nearly all of the Quintel generated datasets will probably use the same 20-30 commit messages, it may be even better still, if technically possible, if these messages only have to be stored once.

Commits are linked to the dataset, so each dataset needs a separate commit when importing.

Reusing commits might be an interesting method to reduce duplication in user (cloned) datasets, but it's not trivial and I'm not familiar enough with how ETLocal clones datasets to know what the fallout might be. I think this is something we could investigate later.

**Comment by michieldenhaan** [comment]
> I'm still a bit confused by we should allow different datasets to have different messages; why would "Region 2" need a different commit message for "ETLocal input field 1-3" than "Region 1"? 

We sometimes have multiple sources with different data quality. E.g. for some regions we have very good quality data on solar roof potential, for other regions we don't and estimate it ourselves (e.g. based on average size of homes). In that case it would be convenient to use different commit messages depending on the source. 

However, I guess this isn't a very strict requirement, especially if we can improve performance by dropping it. One option is to first generate the datasets only using our best quality sources (with zeroes for regions for which data is lacking) and then updating those zeroes with our 'next best guess' (e.g. using "Quintel estimate" as commit message).

Also curious what @ChaelKruip and @jorisberkhout think about this.

**Comment by michieldenhaan** [comment]
> I've also realised that while we can reduce the number of commits created, we cannot do anything about the number of "dataset edits" for which there is one created per value changed. 

Is it possible to set a 'default' default? I.e. all input fields without a database edit/entry will have default value 0 without this number being stored in the database for each input field and each dataset? That would save us a lot of entries since most likely we want to set lots of input fields to zero.

**Comment by ChaelKruip** [comment]
> If we can do away with this requirement, an alternative would be to have a CSV file describing all the data, and a YAML file describing the commit messages. 

> One option is to first generate the datasets only using our best quality sources (with zeroes for regions for which data is lacking) and then updating those zeroes with our 'next best guess' (e.g. using "Quintel estimate" as commit message).

I really like this approach as in my imagination this is how the research process will most like be conducted anyway (i.e., iterative improvements for some of the regions).

**Comment by jorisberkhout** [comment]
I agree with @ChaelKruip and like the approach proposed by @michieldenhaan and @antw as summarised in the previous comment.

**Comment by michieldenhaan** [comment]
> Do you think this is a necessary feature?

I don't think so and agree with your concerns. There will be a demand for custom regions (e.g. a combined dataset of two municipalities that will merge next year) but I'm not sure if ETLocal is the place for that unless we can add these custom regions to the map as well.

> Would it be better if you only had to provide the geo_id in the CSV file?

That would be very nice! These ``geo_id``s resemble Statistics Netherlands area codes so I would expect that every dataset of an area (Quintel and non-Quintel) has the same ``geo_id``.
