### ISSUE TITLE
Enable scaling/validation of derived datasets for Belgium?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#163]
Thanks to @redekok we will soon have two Belgian local datasets in ETLocal (Antwerp and a neighbourhood in Gent). Is it possible to automatically scale these datasets on the ``be`` dataset when exporting them to ETSource? 

Similarly, when making changes to these datasets through the ETLocal front-end, ETLocal validates the changes by doing a Refinery check. I suppose this check is currently based on the NL dataset as well.

@antw How much time would it take to add support for Belgian datasets? 

AFAIK the ETM already supports scaling on BE (see https://github.com/quintel/etsource/blob/master/datasets/antwerpen/antwerpen.derived.ad, which has `base_dataset = be`). I can add a ``parent_values.csv`` to the ``be`` dataset.

The ``geo_id`` of both datasets will start with BE (e.g. Antwerp: BEGM11002)

**Comment by antw** [comment]
> @antw How much time would it take to add support for Belgian datasets?

Currently ETLocal assumes that all datasets have [a base region of `nl`](https://github.com/quintel/etlocal/blob/e4b036d0ff48994f2f983cabbe3b10143b47d4ed/app/models/dataset.rb#L35-L40). It should be simple to move this field to the database so that the new regions could define their county as `be`.

I'm sure there will be knock-on effects, such as the "search" field in the front-end which is also hard-coded to only search for locations in NL. We can extend this to also search for places in BE, but it should be noted that without full dataset coverage for BE it will be possible to successfully search for a location, but not have a dataset which may be edited. Not a dealbreaker, but it's awkward behaviour from a user's perspective.

Anyway... in principle the change should not be difficult.

**Comment by michieldenhaan** [comment]
Thanks! Enabling different base regions in the database is enough for now I think, we can leave the search field as it is.

**Comment by michieldenhaan** [comment]
Closing, this is now possible by specifying a country per region in the database
