### ISSUE TITLE
Where does this code/functionality belong

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#23]
First things first. Editing an `.ad` file through an interface where it's attributes are mapped as keys and inputs was not going to cut it. A user has no idea what a useful demand is for example or what `new_houses_insulation_constant_1` might be. 

Through some lengthy discussion with @dennisschoenmakers and @BerendSmits, we decided that it would be more useful to give the user a limited set of attributes one can edit and analyze our way from those attributes to a set of changes in an *existing* `.ad` file.

The analyzes is now partially done (say 60% (80% in features)) and that raises the question, where should that part of the code live. To elaborate:

```bash
gas_consumption:                    --
electricity_consumption:            -- \
roof_surface_available_for_pv:      --- \
number_of_cars:                     ---- > --- [ DATASET ANALYZES ] -> "<dataset_area>.ad"
number_of_residences:               --- /
number_of_residences_with_solar_pv: -- /
number_of_inhabitants:              --
```

The dataset analyzes bit is written independently of ETLocal and lives as a [separate part](https://github.com/quintel/etlocal/blob/export-changes/app/services/dataset_analyzer.rb) of ETLocal. I'm going to be honest with you, but some parts of the analyzes code don't look that great yet. 

The obvious next step when this analyzes is completed, is that it's going to hook in to the creation of a new local dataset. The creation of a new local dataset is right now done through `rake scale FULL_DATASET=nl DERIVED_DATASET=<name> NUMBER_OF_RESIDENCES=<x>` or by executing the following `Atlas` code:

```ruby
Atlas::Scaler.new(
  ENV['FULL_DATASET'], ENV['DERIVED_DATASET'], ENV['NUMBER_OF_RESIDENCES']
).create_scaled_dataset
```

In combination with the analyzes, you could update this 'scaled' dataset to automatically adjust your dataset for local circumstances.

---

The main question this is raising is, where should this code live? Should it stay here inside of ETLocal or is there a possibility for this to live inside of `Atlas`? Or should this be a separate gem?

**Comment by dennisschoenmakers** [comment]
> The main question this is raising is, where should this code live? Should it stay here inside of ETLocal or is there a possibility for this to live inside of Atlas? Or should this be a separate gem?

To elaborate a bit more on this: I raised this question as we apparently also need a rake task from Atlas? Which rake task is this exactly, @grdw ?

**Comment by grdw** [comment]
@dennisschoenmakers I expanded the issue content, explaining that part.

**Comment by antw** [comment]
> The main question this is raising is, where should this code live? Should it stay here inside of ETLocal or is there a possibility for this to live inside of Atlas? Or should this be a separate gem?

Personally, I don't think Atlas is the place for this since the functionality is specific to ETLocal; other users of Atlas likely have no need for these features. Therefore I would either leave it in ETLocal or extract it to a Gem.

A separate Gem often encourages better separation of concerns between the application and the library (in my experience anyway), but it does also complicate things a bit since it's an extra dependency you need to manage. _Probably_ not worth it unless the "analyzers" grow to be quite large or become useful to other projects.

> we decided that it would be more useful to give the user a limited set of attributes one can edit and analyze our way from those attributes to a set of changes in the .ad file.

A couple of questions:

1. In principle this is fine with me, but I'm a little worried that the complexity could balloon out-of-control and we end up implementing a basic version of ETEngine. I guess that's not really a question. 😆 

2. Does this mean we have to add or update "analyzers" if we add, remove, or rename `.ad` attributes?  It would be nice to have integration tests which could provide us some warning if an analyzer becomes out-of-date and needs to be changed.

3. Presumably this only applies to setting values for `.ad` files, and the ability to set values for initializer inputs is unaffected? Or is that not the case?

4. Could anyone provide some concrete examples of how we'd take a value from the visitor and "analyze" it into concrete values in the dataset? For example, if it's too complicated to ask a visitor for a `useful_demand` what data *are* they providing and how do we derive values from that?

For what it's worth, I think you're right that asking for `investment_hv_net_low`, `employment_local_fraction`, `capacity_buffer_in_mj_s`, `(etc)` relies on the visitor knowing our model in depth, and that's just not reasonable. Making things simpler is a good move. :+1:
