### ISSUE TITLE
Would it be useful to be able to change the area name of duplicated datasets?

### ISSUE THREAD

**Issue by redekok** [quintel/etlocal#249]
For a project, I duplicated the Amsterdam dataset in the front-end of ETLocal. The dataset ID is the only thing that allows me to distinguish the two datasets. Would it be useful to allow users to change the area name of duplicated datasets?

![image](https://user-images.githubusercontent.com/5946498/100590992-6ce11a00-32f5-11eb-9b06-819641a4375f.png)

@antw: For now, could you change the area name of this ETLocal dataset (18511) in the database to Haven-Stad instead of Amsterdam? In order to prevent confusion?

**Comment by antw** [comment]
> For now, could you change the area name of this ETLocal dataset

Done.

**Comment by redekok** [comment]
Thanks @antw!

**Comment by michieldenhaan** [comment]
This may turn out to be tricky. Allowing users to change the area name may have some unintended side effects as the underlying geo ID does not change. So I'm not sure if this should be available to everyone. Since the 'clone' feature is rarely used, I would prefer to spend our ETLocal development time on other issues. Closing (please reopen if you disagree!)
