### ISSUE TITLE
GitHub-links to NL2018 weather year curves do not work

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#314]
For example this link doesn't work, page doesn't exist:

![Screenshot 2021-05-31 at 10 01 19](https://user-images.githubusercontent.com/32833996/120161144-498d1e00-c1f7-11eb-9f85-b41e07750238.png)

The reason for this is that the whole folder is linked to the NL-dataset and not the individual curves: https://github.com/quintel/etsource/tree/master/datasets/nl2018/curves/weather

I have an idea: should we use the same procedure for the NL2018, NL2017, NL2016, nl datasets as for the municipal & neighbourhood datasets? Have these datasets automatically use `nl` as `base_dataset` (using the `nl` curves by default) and only add custom curves to these datasets & remove all symlinks? What do you think @michieldenhaan @antw ?

**Comment by michieldenhaan** [comment]
I'm not sure. Technically, `nl`, `nl2016`, `nl2017`, `nl2018` are all 'full' datasets, so `nl2016`, `nl2017`, `nl2018` are not derived from `nl` like a regional dataset is. In that sense it would be a bit odd if their curves default to `nl` because how are we going to define this behaviour consistently? How do you see this @antw? 

We can symlink the individual curves instead of folders but that maybe has downsides as well. Another option would maybe be to add a default curves folder all datasets automatically take their curves from unless a region specific curve is added to the dataset?

**Comment by marliekeverweij** [comment]
> Another option would maybe be to add a default curves folder all datasets automatically take their curves from unless a region specific curve is added to the dataset?

I like this option, as most datasets use the same curves (from `nl` dataset).

**Comment by antw** [comment]
I've fixed this so that symlinks will be followed by ETLocal, which will show the real file being used (nl/... rather than nl2018/...).

@michieldenhaan is right that the fallback behaviour wouldn't work for nl2016, 2017, and 2018, since these are full datasets.

Besides, the fallback feature currently allows looking up files from at most two directories: the derived dataset dir and the parent dataset dir. It does not support a third (or fourth, etc) directory, which would be needed for either of these suggestions to be possible. It could be added at a later time if managing curves for these datasets becomes troublesome.

**Comment by marliekeverweij** [comment]
Great Anthony!

**Comment by marliekeverweij** [comment]
I see that the appearance of the curves in the front-end has changed. Should we update the translations?

![Screenshot 2021-06-02 at 09 32 39](https://user-images.githubusercontent.com/32833996/120442333-c3eba880-c385-11eb-824c-22894797c753.png)

**Comment by antw** [comment]
That didn't happen locally, but it's definitely a bug. I'll sort it out.

**Comment by marliekeverweij** [comment]
Quick fix!  🏎

**Comment by marliekeverweij** [comment]
Sorry, one more issue I run into. It seems that for regions outside of the Netherlands some curves are not loading, see screenshots below. Mostly the weather year curves, but also for example the electric vehicles:

![Screenshot 2021-06-02 at 11 29 21](https://user-images.githubusercontent.com/32833996/120456795-3b293880-c396-11eb-9635-c55571026841.png)
![Screenshot 2021-06-02 at 11 29 33](https://user-images.githubusercontent.com/32833996/120456811-3e242900-c396-11eb-8963-228af5b0e81e.png)
![Screenshot 2021-06-02 at 11 30 05](https://user-images.githubusercontent.com/32833996/120456831-41b7b000-c396-11eb-834b-1833ae0871d9.png)

**Comment by antw** [comment]
> It seems that for regions outside of the Netherlands some curves are not loading

I fixed this.

> Mostly the weather year curves

Northern Ireland (UK) and Antwerpen (BE) do not have weather curves; they're present only for regions based on the NL dataset.

**Comment by marliekeverweij** [comment]
> Northern Ireland (UK) and Antwerpen (BE) do not have weather curves; they're present only for regions based on the NL dataset.

Good point 😅
