### ISSUE TITLE
Carrier.csv created even when identical to parent?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#315]
We recently updated Groningen from 2016 to 2018 data (ID: 14597). I've manually adjusted the imported electricity emission factor to match the NL2018 value. When exporting the dataset from ETLocal to ETSource, a carrier.csv file is created. However, when comparing this carrier.csv file to the file of the parent dataset (NL2018) the files appear to be identical. I would expect that the file is not generated in this case? When exporting an 'older' 2018 datasets such as Gelderland (ID: 15062) a carrier.csv file is not created (older means: emission factors have not been adjusted manually but have been set in the migration when this feature was added).

<img width="595" alt="image" src="https://user-images.githubusercontent.com/32056448/120661378-7f950100-c488-11eb-971f-04a1e481f817.png">

**Comment by antw** [comment]
Apparently this is because the CO2 per MJ of imported electricity has been changed:

* from: 0.11944454000000002 (as in the CSV)
* to: 0.11944454

The values are practically identical, and were changed for three datasets with the commit message:

> Update to 2018 value as specified by Klimaatmonitor: https://klimaatmonitor.databank.nl/Jive?workspace_guid=d2a70db0-97f7-4f73-b636-3e06f3252d0d

The affected datasets are:

* Borsele (GM0654 / 14523)
* De Fryske Marren (GM1940 / 14544)
* Groningen (GM0014 / 14597)

These three commits were made by yourself last Thursday, and had no other changes. Since I cannot find a migration with a matching commit, I assume they were made through the user interface and not a migration. Although the UI shows values rounded to four decimal places, you can still enter more precise values into the field (and these values are saved as you enter them, not rounded).

---

Regardless of the source of the commits, I expect we need to be less precise in Transformer when determining if a value has changed from the default. I think it should be reasonable to assume two values are the same if their first four decimal places are identical. This might not be future-proof if we want to edit other CSV files, but it should do for carriers.

@michieldenhaan Does this sound okay?

**Comment by michieldenhaan** [comment]
Yes indeed, I used the interface. 

> @michieldenhaan Does this sound okay?

Perfect, thanks for investigating!
