### ISSUE TITLE
Adding a search bar to find your own neighborhood / district / municipality

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#37]
There needs to be an input where you can find your neighborhood / municipality / district

### Technically

**Options:**

1. Mapbox GL Javascript filtering (client-side)

Mapbox GL doesn't have a standard search function but does give you the ability to find an area based on a filter. There's only one problem with this implementation and that is zoom level. You are only able to search features that are visible in the current map. Hidden layers features won't be searched. Also searching is on an exact match only.

2. Searching through a Rails action (server-side)

Every layer in the current map is based on a Shapefile. These Shapefiles can be read with serveral ruby libraries. There are two that I found: [georuby](https://github.com/nofxx/georuby) and [ffi-ogr](https://github.com/scooterw/ffi-ogr). I tried Georuby, but it is painfully slow when it comes to searching through a field of every polygon in a Shapefile. The ffi-ogr gem is a bit better but it's still sluggish.

3. The other way would be to have a `Dataset` of each feature in the map. You can than proceed to search on an area attribute. 

4. `ogrinfo` command line tool

Executing the `ogrinfo` command line tool to query the maps is an option to search features.

5. Write something custom in C/Rust/Elixer?

---

**Comment by grdw** [comment]
I picked number 2 and just searched through the datasets table (for each dataset has a separate database entry).

I'm currently searching for 'Veldhoven' as stated here:

![screen shot 2017-03-28 at 13 43 57](https://cloud.githubusercontent.com/assets/2676542/24403319/a47ebc12-13bc-11e7-94a8-ced4eaee51ee.png)

This however returns my 2 'Veldhovens':
 
![screen shot 2017-03-28 at 13 44 24](https://cloud.githubusercontent.com/assets/2676542/24403330/ad7268d2-13bc-11e7-9205-86b5aad06ccb.png)

In order to tell which is which there needs to be specified in which province this neighborhood / district / municipality lies. This can happen in two ways: 

1. 'Fly' to the area on the map (this would imply knowing the latitude and longtitude of every neighboorhood / municipality / distict which are now unknown/obscured).
2. Make a child-parent connection between Datasets and just tell the user.

**Comment by grdw** [comment]
Including @ChaelKruip

**Comment by BerendSmits** [comment]
> In order to tell which is which there needs to be specified in which province this neighborhood / district / municipality lies.

Could we perhaps also state what kind of area it is, so a municipality, district or neighbourhood?

**Comment by ChaelKruip** [comment]
@antw could you also give your opinion on the solution directions mentioned here?

**Comment by antw** [comment]
> Searching through a Rails action (server-side)

[I also found this](https://github.com/rgeo/rgeo), which can apparently integrate with ActiveRecord. I'm not sure how it compares to the other libraries you have tried.

[There's a library for Leaflet.js](https://github.com/smeijer/leaflet-geosearch) which does map searching – it has a number of other [search](http://leafletjs.com/plugins.html#search--popups) and [geocoding](http://leafletjs.com/plugins.html#geocoding) plugins – but I'm guessing "Mapbox GL" means you've already gone in a different direction?

I'm not too experienced with this myself, but perhaps it would be possible to index the shape files (perhaps using something like Elasticsearch) rather than having to read each one whenever you perform a search? I'm not sure if you would consider this to be worth the complexity, Elasticsearch is probably overkill... depends on how slow the existing search is (and whether you want the power of a real search system).

> Make a child-parent connection between Datasets and just tell the user.

It does seem smart to add some context to the search results. e.g.

> * **Veldhoven**
>  District | Netherlands → Noord-Brabant → Eindhoven
> * **Meerveldhoven**
>   Neighbourhood | Netherlands → Noord-Brabant → Eindhoven

**Comment by grdw** [comment]
Superseded by https://github.com/quintel/etlocal/issues/37

**Comment by grdw** [comment]
> but I'm guessing "Mapbox GL" means you've already gone in a different direction?

Well, Leaflet is basically drawing layers from Mapbox GL - so I thought it would be more convenient to use their API instead of a wrapper like Leaflet.
