### ISSUE TITLE
Missing FLH Hydrogen CHP interface element

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etlocal#455]
Full load hours of hydrogen CHP are missing in ETLocal.
This causes the technology to be incalculable and turned off in ETModel. 

- Interface element should be made
- Migration setting all flh of hydrogen CHP

**Comment by mabijkerk** [comment]
This issue still persists: industry hydrogen heater and CHP are not available on ETModel for Aarhus. However, this issue is only relevant for Aarhus because these units have 0 FLH in the dataset. The interface elements themselves do exist and have existed for quite a while now: https://github.com/quintel/etlocal/blame/production/config/interface_elements/energy/energy_full_load_hours.yml#L227-L228

@Charlottevm is this something you want to solve for Aarhus or can we close the issue?
