### ISSUE TITLE
Documentation on curves should be improved

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etlocal#459]
Multiple questions we receive from ETM users regard the precise calculation/sources behind the curves used in the ETM.
Currently the documentation for curves used in the NL datasets (and many others) is present on our public etdataset github repository.
Other sources for curves are however lacking/difficult to find, especially for users but also for us (they can be in the etm documentation, on etdataset or in a dropbox folder). 

**Proposal:**
1. Must have: Make sure all sources for curves are present & accessible for users
2. Must have: Make it clear which curves are 'copied' (with which sources) and which curves are location-specific concerning a specific dataset
3. Nice-to-have: Store all sources/metadata for curves in one location (preferably ETLocal with the exception of the Dutch curves)

What do you think concerning this topic @redekok @mabijkerk @DorinevanderVlies?

**Comment by redekok** [comment]
Great idea to bring more structure into our curves and its documentation!

**Comment by mabijkerk** [comment]
Sounds good, I think @redekok is assessing the potential for a proposal about profile improvement. Not sure if this can be part of it. I don't fully understand why this is an ETLocal issue though.

Some suggestions:

- I also ran into some difficulties understanding the curves, this might serve as inspiration for improvement, see my discussion with @redekok in https://github.com/quintel/etdataset/pull/966#issuecomment-1419060325 and https://github.com/quintel/etsource/pull/2845#issuecomment-1419078700
- See also this open issue about broken links, https://github.com/quintel/documentation/issues/141
- Finally, one point that seems somewhat unclear to clients is why are curves are normalized to 1/3600 instead of to 1. I'm not sure whether this is well-documented yet - even better would be to make this an explicit factor that is applied to all curves, instead of an implicit factor that is part of the curves
