### ISSUE TITLE
Graph doesn't initialize on the beta-server due to the non-existing energy balance csv files

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#57]
As you can see there are currently sliders on the `beta`-server (because of https://github.com/quintel/etlocal/issues/53) :

![screen shot 2017-05-12 at 13 33 46](https://cloud.githubusercontent.com/assets/2676542/25996453/a84ae3c4-3717-11e7-8dda-1d6b8cfd5839.png)

The only problem is that the defaults are derived from the Dutch graph (with `Atlas::Runner`) which works locally but not on the beta server. The reason for that is that the energy balances are encrypted.

Now there's the easy yet illegal solution (which is decrypting them on the server 🙊). So I'm going to ask the proper question: how does this work properly? Can Atlas work with the `.gpg` files instead of the `csv` energy balances? How would I solve this? How does etengine go about doing this?

**Comment by antw** [comment]
> Can Atlas work with the .gpg files instead of the csv energy balances? How would I solve this? How does etengine go about doing this?

Atlas doesn't work directly with the GPG files since the expectation is that they will be available in decrypted form. Personally I think it best for Atlas to work with the decrypted CSVs since these are what the modellers and researchers will edit. If they have to encrypt the balance each time they want to experiment with a change, it adds an extra step (and annoyance) to their workflow.

> Now there's the easy yet illegal solution (which is decrypting them on the server 🙊). So I'm going to ask the proper question: how does this work properly?

This is basically what ETEngine does. Whenever you import a new ETSource commit [it will decrypt the energy balance files](https://github.com/quintel/etengine/blob/fca2e48e42f6a7691cc0cc4d751ff55943df9fba/app/models/etsource/base.rb#L136-L151). We're not allowed to _redistribute_ the raw CSV files (right @ChaelKruip?) which is why we store them in an encrypted form in ETSource. However, it's perfectly okay for them to be decrypted on our machines including the servers (just make sure they aren't placed into a directory which Nginx serves publicly).

The passphrase is kept private, of course, and not published anywhere in ETEngine. It is placed into the ETEngine `shared` directory [by Ansible](https://github.com/quintel/ansible/blob/f920a0e4ca737cd5d4727c3efe41b31c37eb8bb5/roles/etengine/tasks/main.yml#L31-L37), and [symlinked by ETEngine during deploys](https://github.com/quintel/etengine/blob/fca2e48e42f6a7691cc0cc4d751ff55943df9fba/config/deploy.rb#L36)

**Comment by ChaelKruip** [comment]
> We're not allowed to redistribute the raw CSV files

True. They are commercial data which needs to be bought from the IEA.
